/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `Config`
--
USE `zm`;
LOCK TABLES `zm`.`Config` WRITE;
/*!40000 ALTER TABLE `Config` DISABLE KEYS */;
UPDATE `zm`.`Config` SET `Value`='1' WHERE `Name`='ZM_OPT_FFMPEG';
UPDATE `zm`.`Config` SET `Value`='/usr/bin/ffmpeg' WHERE `Name`='ZM_PATH_FFMPEG';
UPDATE `zm`.`Config` SET `Value`='mpg mp4* mpeg wmv asf avi mov swf 3gp**' WHERE `Name`='ZM_FFMPEG_FORMATS';
UPDATE `zm`.`Config` SET `Value`='-r 30 -vcodec libx264 -threads 2 -b 2000k -minrate 800k -maxrate 5000k' WHERE `Name`='ZM_FFMPEG_OUTPUT_OPTIONS';
UPDATE `zm`.`Config` SET `Value`='1' WHERE `Name`='ZM_OPT_CAMBOZOLA';
UPDATE `zm`.`Config` SET `Value`='/zm/cgi-bin/nph-zms ' WHERE `Name`='ZM_PATH_ZMS';
/*!40000 ALTER TABLE `Config` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
